### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by ali-sattari** [d0u9/youtube-dl-webui#1]
I've installed using recommended procedure: installed youtube-dl and Flask using pip, and then executed python setup.py install, here is the error in middle of outputs:

```
copying build/lib.linux-x86_64-2.7/youtube_dl_webui/core.py -> build/bdist.linux-x86_64/egg/youtube_dl_webui
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_webui/db.py to db.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_webui/server.py to server.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_webui/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_webui/worker.py to worker.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_webui/__main__.py to __main__.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_webui/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_webui/core.py to core.pyc
  File "build/bdist.linux-x86_64/egg/youtube_dl_webui/core.py", line 135
    return {**conf_opts, **d}
             ^
SyntaxError: invalid syntax
```
The error persists while trying to execute newly created youtube-dl-webui command:

```
youtube-dl-webui -h
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl-webui", line 11, in <module>
    load_entry_point('youtube-dl-webui==0.1.dev0', 'console_scripts', 'youtube-dl-webui')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2631, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2291, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2297, in resolve
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl_webui-0.1.dev0-py2.7.egg/youtube_dl_webui/__init__.py", line 7, in <module>
    from .core import Core
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl_webui-0.1.dev0-py2.7.egg/youtube_dl_webui/core.py", line 135
    return {**conf_opts, **d}
             ^
SyntaxError: invalid syntax

```

Please advice.

**Comment by d0u9** [comment]
It seems that you are using python 2.7 shipped with the OS.  I write and test this project under python 3.6.1, and I am not sure if the codes compatible with python 2.7. I suggest you install python 3.6 via [pyenv](https://github.com/pyenv/pyenv), it is fairly simple and manageable for managing various versions of python.
