### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'put'

### ISSUE THREAD

**Issue by theRealKupapa** [d0u9/youtube-dl-webui#20]
On a Windows 10 platform, the GUI loads on the browser but receiving this error.  Any ideas?

config.json

{
    "general": {
        "download_dir": "C:\\Youtube",
        "db_path": "C:\\Users\\User\\youtube-dl-webui\\youtube_dl_webui.db",
        "log_size": 10
    },
    "server": {
        "host": "0.0.0.0",
        "port": 5000
    },
    "youtube_dl": {
        "format": "bestaudio/best",
        "proxy": "socks5://127.0.0.1:1080"
    }
}
-----------------------------------
 * Serving Flask app "youtube_dl_webui.server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://10.1.1.8:5000/ (Press CTRL+C to quit)
10.1.1.9 - - [11/May/2018 14:44:09] "GET / HTTP/1.1" 200 -
10.1.1.9 - - [11/May/2018 14:44:09] "GET /static/font-awesome/css/font-awesome.min.css HTTP/1.1" 200 -
10.1.1.9 - - [11/May/2018 14:44:10] "GET /static/css/modalComponent.css HTTP/1.1" 200 -
10.1.1.9 - - [11/May/2018 14:44:10] "GET /static/css/vue-toast.css HTTP/1.1" 200 -
10.1.1.9 - - [11/May/2018 14:44:10] "GET /static/css/global.css HTTP/1.1" 200 -
10.1.1.9 - - [11/May/2018 14:44:10] "GET /static/js/vue-resource.min.js HTTP/1.1" 200 -
10.1.1.9 - - [11/May/2018 14:44:10] "GET /static/js/vue.min.js HTTP/1.1" 200 -
10.1.1.9 - - [11/May/2018 14:44:11] "GET /static/js/vue-toast.js HTTP/1.1" 200 -
10.1.1.9 - - [11/May/2018 14:44:11] "GET /static/js/global.js HTTP/1.1" 200 -
10.1.1.9 - - [11/May/2018 14:44:11] "GET /static/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 -
**[2018-05-11 14:44:11,522] ERROR in app: Exception on /task/list [GET]**
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\youtube_dl_webui-rolling-py3.6.egg\youtube_dl_webui\server.py", line 42, in list_task
    MSG.put('list', payload)
**AttributeError: 'NoneType' object has no attribute 'put'**
10.1.1.9 - - [11/May/2018 14:44:11] "GET /task/list?state=all HTTP/1.1" 500 -
10.1.1.9 - - [11/May/2018 14:44:12] "GET /favicon.ico HTTP/1.1" 404 -
10.1.1.9 - - [11/May/2018 14:44:12] "GET /favicon.ico HTTP/1.1" 404 -
[2018-05-11 14:44:14,538] ERROR in app: Exception on /task/list [GET]
Traceback (most recent call last):

**Comment by d0u9** [comment]
Fixed.

**Comment by theRealKupapa** [comment]
It works!!  Thank you!!
