### ISSUE TITLE
Fails to add when unable to find description.

### ISSUE THREAD

**Issue by minideezel** [d0u9/youtube-dl-webui#27]
I get the following when trying to download a multipart streaming .m3u8 url:

```
Process Worker-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl_webui-rolling-py3.5.egg/youtube_dl_webui/worker.py", line 118, in run
    info_dict['description'] = info_dict['description'].replace('\n', '<br />');
KeyError: 'description'
```

**Comment by oldiy** [comment]
I also encountered the same problem
