### ISSUE TITLE
NameError: global name 'PermissionError' is not defined

### ISSUE THREAD

**Issue by shaminmv** [d0u9/youtube-dl-webui#33]
I am getting the following error when tried to run :

`root@nginx:~/youtube-dl-webui# youtube-dl-webui -c example_config.json
pid is 898
-----------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl-webui", line 11, in <module>
    load_entry_point('youtube-dl-webui===rolling', 'console_scripts', 'youtube-dl-webui')()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl_webui-rolling-py2.7.egg/youtube_dl_webui/__init__.py", line 27, in main
    core.start()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl_webui-rolling-py2.7.egg/youtube_dl_webui/core.py", line 293, in start
    except PermissionError:
NameError: global name 'PermissionError' is not defined
`

Here is my config
`{
    "general": {
        "download_dir": "/home/pi/Desktop/youtube_dl",
        "db_path": "/tmp/youtube_dl_webui.db",
        "log_size": 10
    },
    "server": {
        "host": "0.0.0.0",
        "port": 5000
    },
    "youtube_dl": {
        "format": "bestaudio/best",
        "proxy": "socks5://127.0.0.1:1080"
    }
}`

Any help?

**Comment by maciejzgadzaj** [comment]
I got it too, when I installed `youtube-dl-webui` with python2 instead of 3. After installing again with `python3 setup.py install` the error disappeared.
