### ISSUE TITLE
Error while trying to run using Docker

### ISSUE THREAD

**Issue by mrbinr** [d0u9/youtube-dl-webui#4]
Hi,
I've tried to use youtube-dl-webui using docker but after docker run i have this error :

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/youtube_dl_webui/youtube_dl_webui/__main__.py", line 20, in <module>
    with open('logging.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logging.json'
`

Any idea about what is missing or else ..

Thanks

Best Regards

mrbinr

**Comment by beutepa** [comment]
Looks like an issue when adding the new logging. 

I tried adapting `__main__.py` to use the full path to logging.json, but then I get a permission denied when the errors.log is was created.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/config.py", line 558, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/lib/python3.6/logging/config.py", line 731, in configure_handler
    result = factory(**kwargs)
  File "/usr/local/lib/python3.6/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/usr/src/youtube_dl_webui/errors.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/youtube_dl_webui/youtube_dl_webui/__main__.py", line 34, in <module>
    logging.config.dictConfig(logging_conf)
  File "/usr/local/lib/python3.6/logging/config.py", line 795, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python3.6/logging/config.py", line 566, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'error_file_handler': [Errno 13] Permission denied: '/usr/src/youtube_dl_webui/errors.log'
```

I rebuild the container using the master branch of youtube-dl-webui and then it works.
You only need to replace the download url from https://codeload.github.com/d0u9/youtube-dl-webui/zip/web_dev to https://codeload.github.com/d0u9/youtube-dl-webui/zip/master in the Dockerfile),

**Comment by wanjeonhanhwang** [comment]
Lastest build image on docker hub have the same error

**Comment by d0u9** [comment]
I have just updated the docker image on docker hub. I used wrong branch in the dockerfile.
