### ISSUE TITLE
Error while trying to run using Docker

### ISSUE THREAD

**Issue by mrbinr** [d0u9/youtube-dl-webui#5]
Hi,

There are still problem using docker image after running command  docker run d0u9/youtube-dl-webui

`pid is 1

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/youtube_dl_webui/youtube_dl_webui/__main__.py", line 17, in <module>
    youtube_dl_webui.main()
  File "/usr/src/youtube_dl_webui/youtube_dl_webui/__init__.py", line 26, in main
    core = Core(args=cmd_args)
  File "/usr/src/youtube_dl_webui/youtube_dl_webui/core.py", line 38, in __init__
    self.db = DataBase(self.conf['db_path'])
  File "/usr/src/youtube_dl_webui/youtube_dl_webui/db.py", line 29, in __init__
    conn = sqlite3.connect(db_path)
sqlite3.OperationalError: unable to open database file`

Best Regards 
Pascall

**Comment by wanjeonhanhwang** [comment]
I can confirm that this happens to me too.

**Comment by d0u9** [comment]
Should be OK now, feedback me if problem is remaining.
